### ISSUE TITLE
duplicate person record

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#114]
I am under the impression that some record should be merged because they refer to the same person, but it should be checked by someone more knowledgeable than me:
- [x] [P3827](https://www.tbrc.org/#!rid=P3827) and [P0RK440](https://www.tbrc.org/#!rid=P0RK440)
- [x] [P0RK825](https://www.tbrc.org/#!rid=P0RK825) and [P8224](https://www.tbrc.org/#!rid=P8224)
- [x] [P8175](https://www.tbrc.org/#!rid=P8175) and [P4255](https://www.tbrc.org/#!rid=P4255)
- [x] [P4266](https://www.tbrc.org/#!rid=P4266) and [P8250](https://www.tbrc.org/#!rid=P8250)
- [x] [P10186](https://www.tbrc.org/#!rid=P10186) and [P7878](https://www.tbrc.org/#!rid=P7878)
- [x] [P4CZ16794](https://www.tbrc.org/#!rid=P4CZ16794) and [P0RK671](https://www.tbrc.org/#!rid=P0RK671)
- [x] [P0RK978](https://www.tbrc.org/#!rid=P0RK978) and [P4CZ15638](https://www.tbrc.org/#!rid=P4CZ15638)
- [x] [P4833](https://www.tbrc.org/#!rid=P4833) and [P856](https://www.tbrc.org/#!rid=P856)
- [x] [P8262](https://www.tbrc.org/#!rid=P8262) and [P00KG07267](https://www.tbrc.org/#!rid=P00KG07267)
- [x] [P0RK166](https://www.tbrc.org/#!rid=P0RK166) and [P4004](https://www.tbrc.org/#!rid=P4004)
- [x] [P8LS14026](https://www.tbrc.org/#!rid=P8LS14026) and [P8249](https://www.tbrc.org/#!rid=P8249)
- [x] [P8LS12737](https://www.tbrc.org/#!rid=P8LS12737) and [P803](https://www.tbrc.org/#!rid=P803) and [P2352](https://www.tbrc.org/#!rid=P2352)

**Comment by karmagongde** [comment]
@lobsangshastri @chungdak @Klhamo
Please check person record and withdrawn the duplicate. Before withdraw select right Person record for those works or outlines as well as other associated links.
1-3 = Chungdak la 
4-6 = Chozin la 
7-9 = Karma 
10-12 Lobsang la

**Comment by karmagongde** [comment]
@eroux 
1. P4266 and P8250 are found different author therefore, it is not a duplicate. 

2. In Among Tibetan Texts: History and Literature of the Himalayan Plateau, page 194. Gene la mentioned P4833 and P856 are two different author.

3. P8175 and P4255 are also different author. one is Indian Pandita and other is Tibetan Translator.

4. Following Person records are Withdrawn because of duplicate, every linked works, outlines teacher student relation and linages are updated in right record: P0RK978, P0RK166, P8LS14026, P8LS12737, P2352, P4833, P0RK440, P0RK1220, P10186, P0RK671 and P0RK825. Therefore, please delete from DLMS record so that, it will not be re-used in future.

5. Also, changed the Master and student relation of P803 and P314.

**Comment by eroux** [comment]
@karmagongde and others: thanks a lot, that's really helpful! Maybe there could be a note in P4833 and/or P856 indicating page 194 of "In Among Tibetan Texts"? That will probably be helpful for other persons!
