### ISSUE TITLE
typical image size (px)

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#151]
@TBRC-Travis I think I would need some help from you on that. 

To handle IIIF presentation API, it's necessary to have the size of images (in px) in advance, and we can't just do that on the fly. So we need a way to prepare some data about the size of all images. What I propose is a `dimensions.json` file in each image group, reading something like:

```json
{
   "I1KG150440001.tif:2": "2500x400",
   "I1KG150440003.jpg:1000": "2300x400"
}
```

where `:2` and `:1000` have the same meaning as in the new item records. The meaning is the following: 
- all file names are in alphabetical order
- take the final 4 characters of the file name without extension (ex: `I1KG150440003` -> 4 last chars = `0003`)
- if they don't convert to an integer, then you can't apply the method, so in this case you just list the file names
- if two consecutive files have the same extension and the same file name except the 4 final chars, and the two final 4 chars convert to consecutive integers, then you can use the first file name and append `:2`, `2` indicating the number of consecutive file names, and you can start again with the next file name

In this context, for filenames to be appended to the list, they also must have the same image dimensions.

In this case the list above can be rewritten as

```json
{
   "I1KG150440001.tif": "2500x400",
   "I1KG150440002.tif": "2500x400",
   "I1KG150440003.jpg": "2300x400",
   "I1KG150440004.jpg": "2300x400",
   "I1KG150440005.jpg": "2300x400"
   ...
}
```

I can write a script to write this .json in a directory (in which language? in Python ok?) but I'll need your help to actually run it and upload the result on S3 (and get a .zip myself too, for migration purposes).

**Comment by xristy** [comment]
The Harvard DRS project involves generating METS data for all the images being deposited and it might be worth looking at generating the[ IIIF manifests from METS](https://github.com/pulibrary/spiiiffy/wiki/How-to-Generate-IIIF-Manifests-from-METS) since a lot of the work is already done during the BatchBuilder METS generation.

**Comment by eroux** [comment]
Oh, that's interesting! So do you think it would be relevant to close this issue and open one on https://github.com/BuddhistDigitalResourceCenter/drs-deposit asking for a dump of the METS metadata that I could, in turn, transform into JSON (or something else) and upload on S3?

**Comment by xristy** [comment]
Sure. Jim Katz is working on the project and is generating batches for all the Works in the archive that have Harvard HOLLIS ids - around 7500 Works. That would be a start. The BatchBuilder could be _tricked_ into generating batch files for additional works (which include the METS info) by reusing HOLLIS ids. That would create useless batches since the bibliographic metadata would be useless but the METS content should be usable.

**Comment by eroux** [comment]
cool! doing that
