### ISSUE TITLE
W3CN616 vol. 3 downloading issue

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#170]
@TBRC-Travis Hi Travis,
We have received an email saying there is download issue with the W3CN616 volume no. 3. Even it is open access, I tried and have same problem. The screenshot of message attached here. 
![screen shot 2018-03-30 at 10 11 30 am](https://user-images.githubusercontent.com/19337852/38140796-6658d068-3403-11e8-97cc-53bc4fb3a386.png)
![image001](https://user-images.githubusercontent.com/19337852/38140808-78c5d6c4-3403-11e8-9728-b815beb73b0d.png)
The second images is from David Lutz who found download problem.

**Comment by TBRC-Travis** [comment]
I downloaded the images for Volume 3 and didn't see any obvious issues.  I tried re-processing the images and removing the image metadata in case that was the issue, but after syncing these updated images and trying again the PDF download still bombs out.

@xristy I'll need your assistance in debugging this further.  I looked in /home/ec2-user/browser/tomcat/logs/localhost.2018-03-30.log to see if I could get more specific info about the error but I don't see anything.

**Comment by xristy** [comment]
Looks like there's a difference between the ImageGroup info and the archive layout for vol 3:

> 30-Mar-2018` 18:30:34.666 INFO [http-nio-15173-exec-7691] org.apache.catalina.core.ApplicationContext.log org.tbrc.gwt.pechaviewer.server.PdfServiceImpl: genDownload access type allAccessRight for W3CN616[I3CN620] pp.1-754 from 70.112.160.248
30-Mar-2018 18:30:34.695 SEVERE [http-nio-15173-exec-7691] org.apache.catalina.core.ApplicationContext.log org.tbrc.gwt.pechaviewer.server.PdfServiceImpl: other exception during pdf generation: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 7A646B04FC51DDA1)
 com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 7A646B04FC51DDA1), S3 Extended Request ID: 2MSd5O4JbPj7N0/0Ri1pzjQtZUIJVQIQR0FnNmeKIZtC4MY7r9NjX4cUZrEPBcRGeeC1NVhcb68=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1305)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)


The problem is that in S3 there are images  I3CN6200001.tif thru I3CN6200632.jpg; but in the image group I3CN620 the ondisk image list is I3CN6200001.tif thru I3CN6200754.jpg so when the pdf gen tries to go past 632 it gets a 404 not found

**Comment by TBRC-Travis** [comment]
Ah yes.  Right.  I did a partial sync and forgot to update the page info.  I've fixed the page info and it's now downloading as it should.  Thanks Chris!
