### ISSUE TITLE
unrestricting W4CZ7445 (lithang)?

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#188]
I noticed that the lithang Kangyur (W4CZ7445) is marked as temporarily restricted... What is the reason for that? rKTs has an outline and I've imported it in the new system.

**Comment by karmagongde** [comment]
The work number W4CZ7445 is marked as temporarily restricted because of the images provider's request. Few volumes are missing in this lithang kagyur and Chozin la is trying to obtain the missing volumes. 
Having outlines for the any kind of restricted are fine. It help to find the individual text with in the collection. We have created outlines for many copyright and restricted texts.

**Comment by eroux** [comment]
Ok, I'm a bit curious about the details as I thought BDRC scanned it... who is the image provider and what is his request? 

Or maybe the ones BDRC scanned are not the ones of W4CZ7445? I think the images of BDRC are the ones provided by Adharsha [here](https://adarsha.dharma-treasure.org/kdbs/jiangkangyur/pbs/1307099).

**Comment by karmagongde** [comment]
The images of Lithang Kagyur in work number W4CZ7445 are from Orissa, and W4PD3142 are from Adharsha. In W4CZ7445 few  volumes are missing and lots page damages by insects. The image of W4PD3142 are in processing stage. volume num 30-33 are still waiting to arrive. Restricted are marked according to the request of owner of the images. I will talk to Jeff about the restrictions and change accordingly.
