### ISSUE TITLE
outlines with locations in the wrong work

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#24]
These outlines declare to be outlines for one work, but have locations in another one:

- [x] O1PD112371 has locations in work W22084 instead of W1PD96682
- [x] O1PD98547 has locations in work W00EGS1016725 instead of W00KG09667
- [x] O00JR968 has locations in work W25983 instead of W30199
- [x] O0UU4 has locations in work 1 instead of W11249
- [x] O4CZ156 has locations in work W1KG10193 instead of W27300
- [x] O01CT0026 has locations in work W20751 instead of W22271
- [x] O2MS815 has locations in work W14612 instead of W2DB4612
- [x] O4JW333 has locations in work W30532 instead of W22084

**Comment by karmagongde** [comment]
I checked the 1 Outline located in 2 work numbers list sent by you in DLMS as well as website and found every work number as it own Outline. Three of them do not have outline. 
Following are according to DLMS as well as website.
W00EGS1016725-O1GS88477
W00KG09667-O1PD98547
W1KG10193-O4CZ22140
W1PD96682-O1PD112371
W2DB4612-O2MS815
W11249-O0UU4
W20751-O20751
W22271-O01CT0026
W23218-O2JT8671
W25983-O003JR198
W27300-O4CZ156
W30199-O00JR968
W22084-O1GS12980 (Not O4JW333)
W14612-No Outline
W23128-No Outline
W30532-No Outline
84000 Structual Outline (O4JW333 and O1JC11494), I’m not sure the work number of these two Outlines. For bka’ ‘gyur/ (sde dge par phud), the outline is O1GS12980. please find and let us know.
Please make correction. Thank you.

**Comment by eroux** [comment]
To take an example of the problem, if you look at [O2MS815](https://www.tbrc.org/xmldoc?rid=O2MS815), it is an outline of [W2DB4612](https://www.tbrc.org/#!rid=W2DB4612), but if you look at the node `O2MS81501JW32105`, title `ye shes la chos nyid mi snang ba la sogs par 'khrul ba'i 'khrul gzhi bstan pa/ `, it says that the end page is in work [W14612](https://www.tbrc.org/#!rid=W14612). In this outline, this is the only node with an error so it is quite easy to fix. Do you see what I mean? For other outlines, many nodes have incorrect locations.

**Comment by karmagongde** [comment]
This example is very helpful. I corrected this one. Rest of the issues also send in same detailed. Thanks!

**Comment by karmagongde** [comment]
Hi Elie,
Could you send me the rest of the above issues just like the example you have sent with title. So that, I can make corrections.

**Comment by karmagongde** [comment]
Hi Elie,
I received and check the errors issue. each issues are listed double. Can you please send again without double listing. Thank you.

**Comment by eroux** [comment]
Here it is: 
[errors-workids-nodups.txt](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/1282033/errors-workids-nodups.txt)

**Comment by karmagongde** [comment]
Received. Thank you.

**Comment by karmagongde** [comment]
We finished making correction of Outlines with two work numbers. But, there are several issue need to be check again. My remarks are in parentheses. 

O2JT86711PD114091 in O2JT8671 of W23218 has locations in work W23128 instead of W23218, title | kun dga' lhun grub kyi gsung 'bum pod dang po/ | (Can you check the real error of this. Both the work numbers are same (W23218).)
-- | -- | --
O2JT86711PD114101 in O2JT8671 of W23218 has locations in work W23128 instead of W23218, title | kun dga' lhun grub kyi gsung 'bum pod gnyis pa/ | (Can you check the real error of this. Both the work numbers are same (W23218).)

O2MS81501JW32105 in O2MS815 of W2DB4612 has locations in work W14612 instead of W2DB4612, title | ye shes la chos nyid mi snang ba la sogs par 'khrul ba'i 'khrul gzhi bstan pa/ | (There is no outline for W14612, who could be W2DB4612 is located in work W14612? In the out line, there is correct work number W2DB4612, I did not find to fix. Please check again and let us know.)
-- | -- | --
O4JW3334CZ90602 in O4JW333 of W22084 has locations in work W30532 instead of W22084, title | The Tantra of Tārāyoginī | (O4JW333 is withdrawn, The original outline of W22084 is O1GS12980. The outline of W30532 is removed.)
O4JW3334CZ90603 in O4JW333 of W22084 has locations in work W30532 instead of W22084, title | The Supplementary Tantra of Tārāyoginī | (O4JW333 is withdrawn, The original outline of W22084 is O1GS12980. The outline of W30532 is removed.)
O4JW3334CZ90634 in O4JW333 of W22084 has locations in work W30532 instead of W22084, title | raktayamāritantra | (O4JW333 is withdrawn, The original outline of W22084 is O1GS12980. The outline of W30532 is removed.)
O4JW3334CZ90674 in O4JW333 of W22084 has locations in work W30532 instead of W22084, title | byang chub snying po'i rgyan 'bum gyi gzungs/ | (O4JW333 is withdrawn, The original outline of W22084 is O1GS12980. The outline of W30532 is removed.)
O4JW3334CZ90866 in O4JW333 of W22084 has locations in work W30532 instead of W22084, title | sred med kyi bus zhus pa'i gzungs/ | (O4JW333 is withdrawn, The original outline of W22084 is O1GS12980. The outline of W30532 is removed.)
O4JW3334CZ90867 in O4JW333 of W22084 has locations in work W30532 instead of W22084, title | nāgadattadhāraṇīnāgahṛdaya | (O4JW333 is withdrawn, The original outline of W22084 is O1GS12980. The outline of W30532 is removed.)
O4JW3334CZ90932 in O4JW333 of W22084 has locations in work W30532 instead of W22084, title | tārābhaṭṭārikānāmāṣṭaśatakam | (O4JW333 is withdrawn, The original outline of W22084 is O1GS12980. The outline of W30532 is removed.)

**Comment by eroux** [comment]
OK, thanks! Everything looks good to me!
