### ISSUE TITLE
Scan request issue

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#26]
Hi Chris,
I received an email from Paldor la stated 1 scan request number for 2 work number was occurred at the Scan-request process. Therefore, please check his machine for this issue. So that, same issue won't happen again.
Here is copy of title pages generated by Machine for two different work numbers with same imageGroup number.
W2PD17384-I3PD1096(v.11)
W3PD1092-I3PD1096
I will be requesting Paldor la to generate new imageGroup for the work numbers which did use existing ImageGroup Number after Checking his Machine.

![w2pd17384-i3pd1096 v 11](https://user-images.githubusercontent.com/19337852/29979512-bd3fb3c8-8f13-11e7-81f4-e5e04b42de11.png)
![w3pd1092-i3pd1096](https://user-images.githubusercontent.com/19337852/29979513-bd406fca-8f13-11e7-96b1-2fb914ffba34.png)

**Comment by xristy** [comment]
There's nothing for me to check on Paldor's computer.

These problems all occurred in 2015 and appear to have been caused by using two or more different computers with copies of the same Workspace or Workspaces that were set up with the same `RID Key` and `RID Counter` in the Editor's "DLMS User Preferences".

There are images in the archive for both `W2PD17384` and `W3PD1092` so one of those sets of images will need to be renamed. Since there's only two volumes in `W3PD1092` it might make sense to rename those, but you and Travis may have other ideas.

The `W2PD17384` was created first on 6 June 2015 in a workspace that had `RID Key` of **`2PD`** and a `RID Counter` around `17380` and apparently published to the db. 

Then 13 hours later that day `W2PD17384` was checked out in a workspace that had `RID Key` of **`3PD`** and a `RID Counter` around `1085`. So either there were two computers in use on 6 June 2015 or someone changed the settings of `RID Key` and `RID Counter` on the original computer from what they were when the record for `W2PD17384` was created to the values that were evidently used to create a Scan Request, `SR3PD1085`, which is how the image groups came to have RIDs `I3PD1086` - `I3PD1115`. The log entries for `W2PD17384` indicate this:

    <entry when="2015-06-06T01:01:13.137Z" who="Paldor">gsar du bcug</entry>
    <entry when="2015-06-06T14:20:59.538Z" who="Paldor"/>
    <entry when="2015-06-06T14:22:35.404Z" who="Paldor">added volumeMap for scan request</entry>
    <entry when="2015-06-14T12:58:15.450Z" who="Paldor"/>

After the scan request, `SR3PD1085`, was completed the `RID Counter` would have had the value `1116`.

But then on 25 June `W3PD1092` was created in a workspace that had `RID Key` of **`3PD`** and a `RID Counter` of `1092` (less than the `1116` where the counter was on 6 June?!

So after `W3PD1092` was created then 18 minutes later scan request, `SR3PD1093` was created along with image groups, `I3PD1096` and `I3PD1097` -- and these RIDs were already used for image groups 19 days earlier?! The log entries for `W3PD1092` indicate this:

    <entry when="2015-06-25T16:05:41.115Z" who="Paldor">gsar du bcug</entry>
    <entry when="2015-06-25T16:09:40.575Z" who="Paldor">zhu dga byas</entry>
    <entry when="2015-06-25T16:23:42.391Z" who="Paldor">added volumeMap for scan request</entry>

Two of the other Works that are involved with the image group conflicts are `W2PD17385` and `W2PD17386`.

I turns out that `W2PD17385` was created on 28 May 2015, 10 days before `W2PD17384` suggesting either another workspace or a resetting of the counter. Further, `W2PD17386` was created on 6 June, a few seconds after `W2PD17384` and then its scan request was created later on 25 June about 3 hours before the scan request for `W3PD1092`.

As I say, it appears that the problems all occurred during 2015 and so whatever was going on in 2015 has stopped or it's no longer generating image group conflicts. It appears that there was some use of multiple copies of workspaces either on the same computer or several computers by one or more users.

Everyone should be aware that they **must not** simply copy a workspace to a new computer and use it *without* changing the `RID Key` and the `RID Counter`.

**Comment by karmagongde** [comment]
Thank you very much for letting us know the detailed on this issue. Now I see how much important everyone should be aware. I forwarded this to Paldor la. It seems he has no GitHub install.

**Comment by xristy** [comment]
No github install is needed. Just web browser with:

https://github.com/BuddhistDigitalResourceCenter/library-issues/issues/26#issuecomment-326689586

ʇǝɹɹǝℲ ǝpoↃ

**Comment by karmagongde** [comment]
Scan request issues are already fixed.
