### ISSUE TITLE
Ignore Kanjur outlines from eXist DB

### ISSUE THREAD

**Issue by jeffwallman** [BuddhistDigitalResourceCenter/library-issues#27]
John Canti reported two problems on tbrc.org.  

1.  W22084 was incorrectly pointed to by O4JW333.  This is incorrect.  Please ignore this outline.  It has been withdrawn.

2.  W22084 also had O1JC11494 pointing to it.  This is also incorrect.  Please ignore this outline.  It has been withdrawn.

3. The correct outline for W22084 is O1GS12980

4. W4CZ5369 has no outline.  O5JW1143 has been withdrawn. This was incorrectly attached to W4CZ5369

**Comment by jeffwallman** [comment]
From Canti

"Dear Jeff,

I hope your epic father-and-son Colorado trek went really well, and look forward to hearing about it!

I’m writing to you with the observations that follow, as I’m not sure who the responsible people might be in your team who can investigate and remedy. Hopefully you can forward them to the right department.

I’ve noticed that since a couple of months ago (June, perhaps?) the outline file that BDRC is using for the Degé par phud Kangyur (W22084) is actually a copy dating from sometime in 2015 of the one I had edited substantially and was initially using for the 84000 Reading Room lobby; long ago we cloned it from your original outline file, which I haven’t accessed myself for a long time. This outline is a ghost-like apparition from the past.

Another, seemingly a little earlier, ghost copy is also in use as the outline for the Rockhill Degé Kangyur in the LoC (W4CZ5369) to which the e-Kangyur search function is linked.

I have no problem at all from a proprietary point of view, but there are some problems:

1) The texts are listed by the outline primarily by their English translation, which is of course not in the original; personally, I would much rather see the Tibetan title, primarily, when I’m browsing the outline in search of a text (though of course there may be users who would appreciate English titles too).

2) The English translations of the titles are often wrong, and in some cases ludicrously so; I’m not sure where they came from, perhaps Arthur’s first draft, but they’re ones we corrected long ago.

3) The data for texts that we’ve subdivided — e.g. Toh 1, the Vinayavastu — into chapters are incomplete and misleading. The Vinayavastu, for example, has 17 chapters only 6 of which are mentioned for W4CZ5369 and 7 for W22084.

4) When users click on Details, they will get puzzling references from the “Translation” nodes (for texts 84000 had completed in 2015) to status (of translations), filenames (of translations), and icons (for the first version of the Reading Room), etc. ; there are also summaries, which people might find useful.

In case it’s any use, I’m attaching a copy of our current outline file, which has the full page data for the chapters of the Vinayavastu and Avataṃsaka. To use with the par phud Degé, the “translation” nodes would probably best be deleted, and some of the other appended details like the section descriptions. Alternatively, there are nodes that could be copied into a revised outline.

I also notice that for volumes 81 and 83 in W4CZ5369, the outline, scans, and e-Kangyur all fail to match each other. These are both volumes at the end of which texts were added in post-par-phud printings like the one the Tohoku catalogue was compiled from, e.g. W30532. Quite why these volumes are different from W22084 in W4CZ5369, I don’t yet know, but the outline file should surely reflect that. And at present the volume view for vol 81 in W4CZ5369 shows page 618 as the last page in the volume, although it clearly isn’t the end of the volume.

Warmest wishes,
John"

**Comment by xristy** [comment]
In a later email John Canti observes:

Regarding the relationship between the different Degé Kangyur sets you have:
- W22084 is the 16th Karmapa’s facsimile of the original par phud print of the Degé
- W3052 is a later (post par phud) print and therefore contains a few changes by comparison with the earlier print. Most notably, it contains two extra texts at the end of vol. 81 and one at the end of vol. 83. It seems to be identical to the print from which the Tohoku catalogue was prepared, which contains those extra texts.
- W4CZ5369 is the Rockhill copy of the Degé Kangyur in the Library of Congress, and seems to be another, different post par phud print. Its vols 81 and 83 have more pages than W22084 but don’t seem to match W3052. TBRC’s text viewer will only show up to p 618 of it, although that page is visibly not the end; without seeing those last pages I can’t investigate it fully (it’s also hard to read), but I suspect some of the the texts have been rearranged into their proper “families”, since the order in W3052  with the addition of the extra texts at the end contravened the “family” order. The eKangyur seems to follow W4CZ5369 in terms of the order of texts.

So it would seem that starting from O1GS12980 and deriving outlines for W3052 and W4CZ5369 might be useful

**Comment by eroux** [comment]
outlines are now imported from rKTs
