### ISSUE TITLE
RID discrepancies

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/library-issues#58]
Looking at [O4CZ2193](https://www.tbrc.org/xmldoc?rid=O4CZ2193), it has the RID `w4CZ2193` which is completely wrong... and all the nodes also start with a `w` instead of an `O`. Here are all the cases:

- [ ] `O23546.xml` has RID `w23546`
- [ ] `O4CZ2193.xml` has RID `w4CZ2193`
- [ ] `O2DB96367a.xml` has RID `O2DB96367`
- [ ] `O1PD86341a.xml` has RID `O1PD86341`
- [ ] `O2DB81174a.xml` has RID `O2DB81174`
- [ ] `O3LS10762-network.xml` has RID `O3LS10762`
- [ ] `O23173.xml` has RID `w23173`
- [ ] `OO1KG988.xml` has RID `O1KG988`
- [ ] `O1PD87842a.xml` has RID `O1PD87842`

**Comment by karmagongde** [comment]
Those are strange to me too. I do not see O23546, O4CZ2193, O23173 in our DLMS. The work number W4CZ2193 has it own outline: O4CZ58182. And some of xml file has "a" at the end of outline number. More detail information would help to know all the issues. By the way, where are those xml files.

**Comment by eroux** [comment]
I do not know how the DLMS works or how you can access the xml files I'm talking about... @xristy maybe you could enlighten us? If they're just erroneous files lurking in the database I'll just ignore them during the migration, no need for this issue...

**Comment by karmagongde** [comment]
I would suggest before migration we should check all the withdrawn and delete them. So we don't have to look again and again on the withdrawn stuffs. There are work number, outline, topic, person, place name.

**Comment by xristy** [comment]
O23546 is indeed withdrawn and should be ignored in the migration.

O4CZ2193 is marked released and claims that its RID is w4CZ2193 which is clearly bogus since its RID should of course be O4CZ2193. When I use the DLMS Editor and checkout O4CZ2193, it is retrieved fine and opens in the editor as expected so I don't know why @karmagongde isn't seeing it. There is a separate outline, O4CZ58182, that is released and also refers to W4CZ2193.

Note that the web site upcases RIDs so if a user enters w4CZ2193 then it "works"

O23173 is marked withdrawn and should be ignored during migration.

So if the migration ignores withdrawn outlines then there is still the case of O4CZ2193 which I have now marked as withdrawn in fsvor of O4CZ58182.

**Comment by eroux** [comment]
Right, I didn't realize that the test I made was before the status test, so with `O4CZ2193` now withdrawn, this issue can be closed... thank you!
