### ISSUE TITLE
eText need to convert into Word document

### ISSUE THREAD

**Issue by karmagongde** [BuddhistDigitalResourceCenter/library-issues#84]
@xristy @eroux @TBRC-Travis 
TBRCRS3/Incoming/scans/Inbox/Sheehy Hard Drive Recovered/Rare Jonang ETC/ETexts

**Comment by xristy** [comment]
Here's the text from the html files:

[Sheehy_Hard_Drive_Recovered-Rare_Jonang_ETC-ETexts-AS_TEXT_UTF8.zip](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/1542937/Sheehy_Hard_Drive_Recovered-Rare_Jonang_ETC-ETexts-AS_TEXT_UTF8.zip)

Here's the original directory from the RS3 incoming

[Sheehy_Hard_Drive_Recovered-Rare_Jonang_ETC-ETexts-FROM_RS3.zip](https://github.com/BuddhistDigitalResourceCenter/library-issues/files/1542938/Sheehy_Hard_Drive_Recovered-Rare_Jonang_ETC-ETexts-FROM_RS34.zip)

Someone else can convert to Word docs. We don't have more time to spend on this issue

**Comment by karmagongde** [comment]
Thank your converting txt files. I downloaded them.

**Comment by eroux** [comment]
I'm a bit confused, what is the purpose of the conversion in Word format? Why not TEI like our other etexts?

**Comment by xristy** [comment]
I assume that someone somewhere wanted the texts for something. I just extracted the actual content which has some pagination info inline. It can be processed later for use in the growing etext corpus but is otherwise not a high priority I think. Usually these requests arise from some grad student or post doc that is wanting the material for research purpose
